### ISSUE TITLE
按键宏该怎么使用？

### ISSUE THREAD

**Issue by csdf** [Lotlab/nrf52-keyboard#100]
按键宏在哪里添加？

是不是在keymap_plain.c 添加ACTION_MACRO(0)，只有看到在data_storage.c有处理id为0的流程，该怎么使用？

**Comment by jim-kirisame** [comment]
若需要使用代码配置按键宏，请关闭MACRO_STORAGE宏，并使用传统的TMK方式实现`action_get_macro`方法，然后添加ACTION_MACRO(x) 作为按键定义即可。
