### ISSUE TITLE
还没支持#define LESS_IO  //键盘阵列采用更少的IO口吗？

### ISSUE THREAD

**Issue by jeromeli002** [Lotlab/nrf52-keyboard#101]
还没支持#define LESS_IO  //键盘阵列采用更少的IO口吗？
用格老师的分支编译出来灯效有些不能用，切换到不能用的灯效灯不亮
用这个代码编译出来不能用，col和row用的相同脚，出现一插电连电脑就触发很多键的现象

**Comment by jim-kirisame** [comment]
欢迎pr。

其他分支的问题请找对应的维护者。
