### ISSUE TITLE
关于开发编译的问题

### ISSUE THREAD

**Issue by lxj5891** [Lotlab/nrf52-keyboard#102]
1. 这个固件  协议栈如何编译，跟烧录，    协议栈 跟bootloader是什么关系，    是否都需要？
2. 如何用jlink swd的链接方式烧录固件。
3. 如何用jlink debug 程序

**Comment by jim-kirisame** [comment]
1. 百度
2. 百度
3. 百度

**Comment by lxj5891** [comment]
nrf52芯片资料  太少了   讲得也不全。。。
