### ISSUE TITLE
capslock灯始终是一半亮度

### ISSUE THREAD

**Issue by wytalfred** [Lotlab/nrf52-keyboard#106]
用的别人给的板子，不知道灯连在哪个引脚。自带的固件灯是可以正常工作的。我自己改的代码就一直半亮不亮的状态，按什么键都没反应。
我已经对LED_CAPS遍历尝试了所有引脚序号，都不行。
除了io口序号以外，还有哪些代码可能跟这个有关呢？

**Comment by jim-kirisame** [comment]
建议检查硬件，看上去是硬件问题。

**Comment by wytalfred** [comment]
> 建议检查硬件，看上去是硬件问题。

有没有可能把ws2812 rgb彩灯用作大写指示灯呢？

**Comment by jim-kirisame** [comment]
需要自行撰写相关事件处理代码。
