### ISSUE TITLE
如何设置多于32个fn_actions?

### ISSUE THREAD

**Issue by wytalfred** [Lotlab/nrf52-keyboard#107]
我想把shift+按键的所有符号设为单独的key，这些符号就有20个，再加上切层、蓝牙、macro什么的，32个不够用呀。。
看了tmk的github和issue，没有明确的解决方案。想问问这里有没有人知道。（有人说用unimap，但具体怎么实现呢？）

**Comment by jim-kirisame** [comment]
使用action map

**Comment by wytalfred** [comment]
> 使用action map

请问有样例代码吗？谢谢

**Comment by jim-kirisame** [comment]
这个库里面没有，请去tmk里面找，具体关键字应该是ACTION_MAP

**Comment by wytalfred** [comment]
> 这个库里面没有，请去tmk里面找，具体关键字应该是ACTION_MAP

好的，谢谢
