### ISSUE TITLE
docker环境下 make -j 报错 make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by Bill-lulu** [Lotlab/nrf52-keyboard#120]
我用的是win11下的docker，容器是wsl的Ubuntu。

**Comment by Bill-lulu** [comment]
![image](https://github.com/Lotlab/nrf52-keyboard/assets/13778451/36e60933-4cba-480f-9d42-a3d3a1372eaa)
我已经运行好多次了，就是这样，你们的docker，我看到tmk文件夹确实少文件

**Comment by Bill-lulu** [comment]
我是不是需要更新一下，git？

**Comment by Bill-lulu** [comment]
关闭一下，我重新提交问题

**Comment by Bill-lulu** [comment]
![image](https://github.com/Lotlab/nrf52-keyboard/assets/13778451/0924a483-12ce-46ac-9601-6388ea03dc35)
我在docker下，重新拉文件再配置，还是这样！

**Comment by jim-kirisame** [comment]
请看编译教程。wiki.lotlab.org

**Comment by Bill-lulu** [comment]
我照着教程一步一步来的！我在两台电脑上，不同的环境下都试了。docker，wsl linux子系统。都报这个找不到配置参数或者文件

**Comment by Bill-lulu** [comment]
cd keyboard/template
make -j

这个是要我去keyboard里面找template，你们SDK下面还有个template（就是让我改名Makefile.posix那个文件夹）呼呼，我没注意这个点。谢谢，编译成功了
