### ISSUE TITLE
nRF52810可以使用softdevice S132吗？

### ISSUE THREAD

**Issue by HaoboGu** [Lotlab/nrf52-keyboard#125]
你好，我正在给 [rmk](https://github.com/haobogu/rmk) 添加nRF52810的支持。请问作者有没有尝试过为nRF52810使用softdevice s132呢？我目前在仓库里只看到有使用s112。我想用s132是因为，它包含了central部分的实现，这在分体里面是很有用的。由于现在用nRF52810的比较少，所以冒昧在这里问一下，感谢！

**Comment by jim-kirisame** [comment]
时间有点久远不太记得了，可以看看nrf官方sdk的帮助说明，应该是能用的。不过52810的资源比较有限，上了s132之后可能资源不是特别够了。
