### ISSUE TITLE
如果使用ws2812当做状态灯，这样可以用一个引脚pwm来实现显示，同时包括大小写和num？

### ISSUE THREAD

**Issue by ada19911201** [Lotlab/nrf52-keyboard#18]
代码部分看了，用户事件蓝牙连接和电池电量是怎么传入参数的

**Comment by ada19911201** [comment]
在main.h中定义了枚举user_ble_event，但是没找个系统怎么判断那种状态的

**Comment by jiangming1399** [comment]
电池电量并没有参数，蓝牙连接的事件在ble_services.c里面触发

**Comment by ada19911201** [comment]
@jiangming1399  想在里面加些功能，如果进行调试怎么进行，之前用的Keil，您这个是用makefile写好的，所以不太会玩

**Comment by jiangming1399** [comment]
我这边用的是DAPLink+PyOCD+GDB来调试的，你应该也可以用JLINK+GDB啥的调试
