### ISSUE TITLE
ch554烧录成功 nrf52怎么烧录呢

### ISSUE THREAD

**Issue by z8806c** [Lotlab/nrf52-keyboard#19]

**Comment by jiangming1399** [comment]
用jlink或daplink刷进去就行。make flash_softdevice和make flash

**Comment by z8806c** [comment]
有没有 简单点的工具 类似ch554 这样的  daplink 搞环境装python2.7  看的头晕目眩 。。。。

**Comment by jiangming1399** [comment]
没有

**Comment by z8806c** [comment]
谢谢了 我再研究研究 好像jlink简单点
