### ISSUE TITLE
请问下大佬，nrf52840是否一样适用呢？刚好多买了几块52840.

### ISSUE THREAD

**Issue by gritJack** [Lotlab/nrf52-keyboard#24]

**Comment by jiangming1399** [comment]
手上暂时没有52840的设备，所以也暂时不支持52840。按理来说改一下编译用的宏和ld文件就能在52840上跑，但要用52840上的usb的话就需要更多的工作去支持。

**Comment by gritJack** [comment]
> 手上暂时没有52840的设备，所以也暂时不支持52840。按理来说改一下编译用的宏和ld文件就能在52840上跑，但要用52840上的usb的话就需要更多的工作去支持。

好滴，谢谢大佬，请问大佬用的是什么调试的，自己一直用keil。

**Comment by jiangming1399** [comment]
gdb+pyocd
