### ISSUE TITLE
请问基于tmk/qmk作为键盘功能的基础大体区别是什么呢(基于qmk是否更方便后续的开发)

### ISSUE THREAD

**Issue by SunRain** [Lotlab/nrf52-keyboard#37]
如题,因为发现qmk好久没有更新了,反而基于tmk加强的qmk开发的很活跃,而且qmk带了很多的外围驱动/实现.
qmk的地址 https://github.com/qmk/qmk_firmware
另外issue里面某位老兄说的52840的参考 https://github.com/chie4hao/qmk_firmware_nrf52840

**Comment by SunRain** [comment]
只是一点不成熟的建议,因为我也在学习自己做一个开源机械键盘,所以最近在找这方面的东西:)

**Comment by jiangming1399** [comment]
qmk主要是一些外围驱动比较多，但是在这个项目中如果要那些驱动就需要有针对的对这个芯片优化，所以我就选择了tmk。
至于52840的支持，只是没时间+没硬件调试而已，真要支持起来还是非常简单的。

**Comment by jiangming1399** [comment]
tmk的不活跃还是因为作为一个基础的键盘库，已经算是非常的完善了。QMK只是在其基础上添加了很多花里胡哨的东西，所以你会看到它还在非常活跃的开发。
