### ISSUE TITLE
关于oled外设的疑问

### ISSUE THREAD

**Issue by kikko233** [Lotlab/nrf52-keyboard#38]
大佬你好，我看到你的固件更新移植了一些外设的支持
所以我想给键盘加一个oled，翻遍了qmk文档都没有发现要求定义oled针脚的语句
在32u4这款mcu上oled是直接接在它的硬件i2c接口上的
而nrf52这款芯片我发现它有俩硬件i2c接口【但是还不知道是哪个针脚hhh】
我应该怎样接线呢
定义方式是不是和qmk的语句一样呢
感谢你的回答

**Comment by jiangming1399** [comment]
nrf52的i2c/spi等io是随意接的，所以直接接上去就行。
定义方式请参考对应的文档。OLED的支持暂时只是一个128*32的屏幕，没有做很多额外的东西，所以效果应该不是很好。

**Comment by jeromeli002** [comment]
试了下，发现只显示个电池usb蓝牙数字键盘 大写128x64的下半部分显示的像半个logo，

**Comment by jim-kirisame** [comment]
@jeromeli002 是的，具体显示没完全做完，所以会出现半个Logo。

**Comment by jeromeli002** [comment]
OLED还会继续更新吗？还是没计划加上了？，虽然这个OLED没什么卵用，但有OLED多一个选择还是好的。

**Comment by jim-kirisame** [comment]
@jeromeli002 暂时没有空闲更新。现在这个OLED算是能用而已的状态，如果要实现更多功能的话就得自己实现一下了。

**Comment by jeromeli002** [comment]
OLED相关是要修改那个文件？
