### ISSUE TITLE
nrf52_kbd.dat 有什么用?

### ISSUE THREAD

**Issue by barryjim** [Lotlab/nrf52-keyboard#44]
在nrf52固件包中nrf52_kbd.dat有什么作用,烧写时是否要用?

**Comment by genokolar** [comment]
zip升级包请勿解压

**Comment by barryjim** [comment]
你好,这个不解压如何升级,能加个好友吗?&nbsp; qq&nbsp;461746775



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Geno [格诺]"<notifications@github.com&gt;; 
发送时间: 2020年7月13日(星期一) 下午4:16
收件人: "Lotlab/nrf52-keyboard"<nrf52-keyboard@noreply.github.com&gt;; 
抄送: "断蓝"<461746775@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Lotlab/nrf52-keyboard] nrf52_kbd.dat 有什么用? (#44)





 
zip升级包请勿解压
