### ISSUE TITLE
Expose debounce settings to online builder

### ISSUE THREAD

**Issue by lightingghost** [Lotlab/nrf52-keyboard#46]
Hi Developers,

Thank you for making this project. 

I found random double clicking for many keys on my keyboard and I want to increase the debounce time. Currently it seems the only way is to compile the firmware by myself. But I would appreciate it if you can expose the debounce settings in the online firmware builder (http://test.glab.online:10086)

btw, I am not sure if this is correct project to raise this issue, please advice where I should post if not.

**Comment by jim-kirisame** [comment]
The online firmware builder is maintain by @genokolar , you could ask him to expose that setting for you.
