### ISSUE TITLE
led的一些问题

### ISSUE THREAD

**Issue by cooliangzhu** [Lotlab/nrf52-keyboard#49]
参考你的Lot60-BLE-Keyboard里的电路 设置了某个引脚做大写锁定 指示灯的引脚, LED上拉驱动, 电路是电源正极接led,然后再链接到某引脚上, 发现开启大写的时候led是灭的, 大写关闭的时候led亮起,  代码就是这么设置的, 还是我链接的方式有问题?

**Comment by jim-kirisame** [comment]
上拉驱动IO接LED正极，LED负极接GND

**Comment by cooliangzhu** [comment]
所以就是我使用led 上拉这种模式的时候  接线反了是吧, 晚上回去再试试, 然后再确认一下, 其他的led 比如蓝牙设备灯 是不是跟这个使用的同样的模式?
