### ISSUE TITLE
NRF51822编译问题

### ISSUE THREAD

**Issue by tongzv1998** [Lotlab/nrf52-keyboard#50]
您好，我在烧录“nrf52-keyboard”代码后，搜索不到设备，不知是选择编译“config.h”不对，还是其他问题，期待您的回复。
![1](https://user-images.githubusercontent.com/59648167/92388613-2b9ffa80-f14a-11ea-91b0-76e39c8e3e6d.png)
![2](https://user-images.githubusercontent.com/59648167/92388622-2e025480-f14a-11ea-9efc-554d2c5e7b32.png)

**Comment by jim-kirisame** [comment]
你当前使用的是老版本（nrf51822）的配置文件，请参考此项目的ble4100配置文件重新配置。
