### ISSUE TITLE
关于Issue #47 #48 nrf52832编译bootloader出错原因

### ISSUE THREAD

**Issue by SunRain** [Lotlab/nrf52-keyboard#54]
爬了一下代码,发现是这里的问题

> 在SDK/external/micro-ecc/nrf52nf_armgcc/armgcc/Makefile的37行,使用的是CFLAGS += -mfloat-abi=soft
和
> application/bootloader/project/nrf52832.mk 14行的CFLAGS += -mfloat-abi=hard -mfpu=fpv4-sp-d16 冲突

所以开启NRF52_DISABLE_FPU宏以后可以编译通过.不过,是否可以复制一份sdk里面的makefile,将micro-ecc的编译规则也放到application/bootloader下呢

**Comment by jim-kirisame** [comment]
对于52810，请用不带hf的版本
