### ISSUE TITLE
关于"关闭指示灯功能"

### ISSUE THREAD

**Issue by maboloshi** [Lotlab/nrf52-keyboard#56]
当L键设置为"普通L, 同时按下RShift是:" 会使"关闭指示灯功能"LShift +RShift +L"失效
<img width="371" alt="截屏2020-11-24 下午8 48 14" src="https://user-images.githubusercontent.com/7850715/100097969-47d54d00-2e98-11eb-935f-4e438e3253a9.png">

**Comment by jim-kirisame** [comment]
@genokolar 你来看看

**Comment by genokolar** [comment]
是这样的，回头看看可否解决

**Comment by genokolar** [comment]
已经修正，后续发布固件版本
