### ISSUE TITLE
使用Rshift搭配的内置功能是否可以添加对RCtrl键支持

### ISSUE THREAD

**Issue by maboloshi** [Lotlab/nrf52-keyboard#57]
<img width="396" alt="截屏2020-11-24 下午8 39 09" src="https://user-images.githubusercontent.com/7850715/100095397-5f5f0680-2e95-11eb-8331-2f7b788711e8.png">

**Comment by genokolar** [comment]
暂时可以通过在线编译，选择使用双ctrl 或 win+esc 来启用 内置功能
