### ISSUE TITLE
新固件切层反应巨慢

### ISSUE THREAD

**Issue by aotsukiqx** [Lotlab/nrf52-keyboard#63]
在 Omega45 和 NewHope64 更新新固件并通过 usb 方式更新排列后再使用按下切层输入第二层字符或触发宏的时候要等 1 秒以上才会正确触发。
比如第一层是字符，第二层设置了数字，当要输入数字时需要按下 LT2+要输入的数字按键，这时需要观察屏幕确定正确输入数字后才能松开 LT2 按键，等待时间要 1 秒以上。但是当正确输入第一个数字后，在未松开 LT2 的前提下继续输入其他数字则输入速度正常，所以判断是切层判断的等待时间过长。
因为已经都刷了新固件，且老固件未保留，对每天的日常使用带来巨大麻烦，请安排修复，谢谢~

**Comment by aotsukiqx** [comment]
使用的是v1.1.3.2版本固件

**Comment by jim-kirisame** [comment]
我这边没有类似的问题， @genokolar 你那边有吗

**Comment by genokolar** [comment]
没有问题。建议采用我编译的固件

**Comment by aotsukiqx** [comment]
在 glabwiki 下载了 11 月的固件，更新后确认没有这个问题了。

**Comment by aotsukiqx** [comment]
关闭 issue
