### ISSUE TITLE
这么编译带DFU的bootloader 和带dfu+bootloafer+键盘 的完整固件？？？

### ISSUE THREAD

**Issue by jeromeli002** [Lotlab/nrf52-keyboard#67]
这么编译带DFU的bootloader 和带dfu+bootloafer+键盘 的完整固件？？？

**Comment by jim-kirisame** [comment]
make bootloader
make merge_all
具体请看make help

**Comment by jeromeli002** [comment]
Merging program, signature and SoftDevice s112_nrf52_6.1.1_softdevice.hex to _build/nrf52_kbd_sign_with_sd.hex
mergehex -m ../../SDK/components/softdevice/s112/hex/s112_nrf52_6.1.1_softdevice.hex _build/nrf52_settings.hex _build/nrf52_kbd.hex -o _build/nrf52_kbd_sign_with_sd.hex
make: mergehex: 没有那个文件或目录
make: *** [../../application/main/project/app.mk:375：merge_all] 错误 127

到最后出错了 nrf52_kbd_sign_with_sd.hex按提示发现没有这个文件

**Comment by jim-kirisame** [comment]
装mergehex

**Comment by jeromeli002** [comment]
编译指南是没有更新还是有错误？？
编译bootloader这步不一样？？
```
# 方法1：
   cd application/bootloader/project/armgcc/
   make SOFTDEVICE=S132 NRF_CHIP=nrf52832 NRF52_DISABLE_FPU=yes -j # nrf52832的编译命令
project/下没有 armgcc 这个目录。如果只进project/ 再执行下一步命令就一堆错误
```
如果用这样
 ```
# 方法2：
   cd keyboard/template
   make bootloader -j

只有tempplate和lkb-core 目录才编译成功其他目录的都是失败
如果把52832改成52810也就能编译通过

_Compiling file: oberon_backend_hash.c
Compiling file: oberon_backend_hmac.c
Linking target: /home/jl/nrf52-keyboard/keyboard/newhope64/_build/nrf52_bootloader.out
arm-none-eabi-gcc: error: ../../../SDK/external/micro-ecc/nrf52hf_armgcc/armgcc/micro_ecc_lib_nrf52.a: No such file or directory
make[1]: *** [../../../template/Makefile.common:293：/home/jl/nrf52-keyboard/keyboard/newhope64/_build/nrf52_bootloader.out] 错误 1
make[1]: 离开目录“/home/jl/nrf52-keyboard/application/bootloader/project”
make: *** [../../application/main/project/bl.mk:19：bootloader] 错误 2_


```

这是哪步出错了？？？

**Comment by jim-kirisame** [comment]
自行修改路径编译uecc库

**Comment by jeromeli002** [comment]
git submodule init -- # 初始化子模块，用于构建microecc库
   cd SDK/external/micro-ecc/nrf52nf_armgcc/armgcc
   make # 编译microecc库
   cd ../../../../../

是这个吗？
这个已经改过了没有报错 下一步就不行了

**Comment by jim-kirisame** [comment]
我已经更新了教程，跟着里面走应该就没问题了。

**Comment by jeromeli002** [comment]
感谢大佬指导小白 
 编译过了
