### ISSUE TITLE
最后一列无效，这个col和row数量有限制的吗？

### ISSUE THREAD

**Issue by jeromeli002** [Lotlab/nrf52-keyboard#70]
这个col和row数量有限制的吗？
想把手里的104键的键盘改成无线的没结果编译好后发现col最后一列不能用
现在设置的是6x17的矩阵，编译完刷入发现第17列无效，换其他脚也不行，其他都正常。
这个固件最多可以 设置多少行多少列？求大佬指教

**Comment by jim-kirisame** [comment]
是bug，刚刚修了，你重新拉取最新的代码吧。

**Comment by jeromeli002** [comment]
非常感谢大佬的及时更新，顺便再问下 row 行有限数量制吗？？

**Comment by jim-kirisame** [comment]
应该没有。
-----
顺便问一句，你开的PR的意图是？

**Comment by jeromeli002** [comment]
还有个问题，大写灯 状态灯……共用脚时候，灭灯后第一次按大写灯不能亮 要再次开启大写才会亮，
大写灯单独脚没这问题，一次就能亮，不知道是bug还是软硬件先天不足。

**Comment by jim-kirisame** [comment]
电路图？

**Comment by jeromeli002** [comment]
就是开源lotlab那图图[](url)
![image](https://user-images.githubusercontent.com/5648129/108830999-ab405980-7604-11eb-82a3-fb9e7130ea18.png)

**Comment by jim-kirisame** [comment]
这个生成器可能没有处理过这样的共用引脚，不建议这么干。

**Comment by jeromeli002** [comment]
发现Num lock灯没有用……在线编译站的不知是手抖多删了还是还是正常减掉的，
#define LED_NUM 这行不会生成，但网页上又有这个选项。
 不知道有没有一份所有配置都有的完整配置文件供参考？
