### ISSUE TITLE
ws2812第一个灯不能控制的吗？

### ISSUE THREAD

**Issue by jeromeli002** [Lotlab/nrf52-keyboard#77]
ws2812第一个灯不能控制的吗？插着usb第一个灯关不了，不插usb开源关闭。第一个灯在很多效果下不亮，
睡眠时第一个灯亮绿色不灭，关闭rgb后休眠第一个灯还是会亮绿色。

**Comment by jim-kirisame** [comment]
@genokolar

**Comment by genokolar** [comment]
驱动没有问题。请看看自己的硬件
