### ISSUE TITLE
编码器只能一个还是可以加几个？

### ISSUE THREAD

**Issue by jeromeli002** [Lotlab/nrf52-keyboard#78]
你好
编码器只能一个还是可以家几个？
一个编码器试过了可以用，不知道能不能有几个编码器
如果可以有相关文档吗？

**Comment by jim-kirisame** [comment]
暂时不行，只支持一个。如果你要支持多个的话，可以修改源代码实现。

**Comment by jeromeli002** [comment]
应该修改哪里的源代码？ 有可以参考的吗

**Comment by jim-kirisame** [comment]
编码器驱动里面的那个
