### ISSUE TITLE
编译了个52811的发现烧录到96%就出错了但按键有效

### ISSUE THREAD

**Issue by jeromeli002** [Lotlab/nrf52-keyboard#84]
![image](https://user-images.githubusercontent.com/5648129/131222337-eda3c0e9-9c57-4fc4-a16c-a37d75614975.png)
编译了个52811的发现烧录到96%就出错了，但按键有效，也能蓝牙能连接，这样有问题吗，这是什么问题？
按52810改的，是不是52810不支持rgb和OLED？这样52811也不支持了

**Comment by jim-kirisame** [comment]
52811的内存布局和52810可能有差异，你可能需要更新pyocd来正确烧录
