### ISSUE TITLE
现在不能显示电量了吗？

### ISSUE THREAD

**Issue by jeromeli002** [Lotlab/nrf52-keyboard#97]
现在不能显示电量了吗？前版本电量还能显示 虽然不是很准
更新后现在一直都显示100% 就是没电了快不能开机也是100%

**Comment by jeromeli002** [comment]
> 可能是bug。能不能提供一下两个版本的提交号吗？


上一版本不知道是不是在更新这个以前的，拆分battery检测与bas service
不能显示电量是最新版本

**Comment by jeromeli002** [comment]
> 可能是bug。能不能提供一下两个版本的提交号吗？


上一版本不知道是不是在更新这个以前的，拆分battery检测与bas service
不能显示电量是最新版本

**Comment by jim-kirisame** [comment]
@genokolar 你来看看？

**Comment by genokolar** [comment]
不清楚，我的好好的啊

**Comment by jeromeli002** [comment]
> 不清楚，我的好好的啊

难道蓝牙模块阵亡了？可是刷回旧版本又能显示电量。
耗电也非常快，模块是ND04。用的遥控飞机电池300mah的，好像也是有休眠的，20分左右不动连接的设备也断开收不到信号。充满电不用一天一晚就没电了。同样的硬件以前完全正常的。
还有就是指示灯用的共阳极RGB灯。28、29、30三个脚。关闭所有灯后接30的还是亮着不会灭。用共阴极RGB可以全关闭。指示灯不能修改上拉或下拉吗？

**Comment by jeromeli002** [comment]
> 不清楚，我的好好的啊
退回这个版本编译出来就可以显示电量变化，最新一直显示100%电量
![image](https://user-images.githubusercontent.com/5648129/139681372-050406f4-a44e-49ff-af6c-869f8d2864d0.png)

**Comment by genokolar** [comment]
仔细核对了代码，应该没有错漏。  因为我的代码分支和这个主分支有一些差异，所以可以问问其他采用这个代码的人有否问题。

**Comment by genokolar** [comment]
终于知道你说什么了。是蓝牙连接设备，设备显示的电量一直是100%。因为我一直用输出电量查看的电量，所以没发现这个问题。

**Comment by jeromeli002** [comment]
> 终于知道你说什么了。是蓝牙连接设备，设备显示的电量一直是100%。因为我一直用输出电量查看的电量，所以没发现这个问题。

你的分支rgb灯效是不是精简了几个，切换有几个灯效不亮 。lotlab的都能亮

**Comment by genokolar** [comment]
当然，没有

**Comment by jim-kirisame** [comment]
应该已经修复了。如果没有的话可以重新开启issue
